"""Generalized Cross-Validation (GCV) criterion."""

from __future__ import annotations

from collections.abc import Collection
from typing import TYPE_CHECKING, Any, overload

import matplotlib.axes
import matplotlib.figure
import numpy as np
from matplotlib import pyplot as plt
from scipy.optimize import OptimizeResult, basinhopping

from ._base import Criterion

if TYPE_CHECKING:
    from .._base import _SVDBase

__all__ = ["GCV"]


class GCV(Criterion):
    """Generalized Cross-Validation (GCV) criterion.

    .. note::
        The theory and implementation of GCV criterion can be seen :doc:`here </theory/gcv>`.
    """

    def __init__(self) -> None:
        self._solver: _SVDBase | None = None

    def gcv(self, solver: _SVDBase, beta: float) -> float:
        r"""Calculate of GCV criterion function.

        GCV function :math:`\mathcal{G}(\lambda)` can be expressed with SVD components as:

        .. math::

            \mathcal{G}(\lambda) = \frac{\rho}{\left[r - \sum_{i=1}^r f_{\lambda, i}\right]^2}.

        Parameters
        ----------
        solver
            An `~._SVDBase` instance providing ``rho``.
        beta
            Regularization parameter.

        Returns
        -------
        float
            Value of GCV function at a given regularization parameter.
        """
        return solver.rho(beta) / (solver.s.size - np.sum(solver.filter(beta))) ** 2.0

    def optimize(
        self,
        solver: _SVDBase,
        bounds: tuple[float, float],
        stepsize: float = 10,
        **kwargs: Any,
    ) -> tuple[float, OptimizeResult]:
        """Find the optimal parameter by minimizing GCV with basinhopping.

        Parameters
        ----------
        solver
            An `~._SVDBase` instance.
        bounds
            ``(log10_lower, log10_upper)`` search interval.
        stepsize
            Step-size for the underlying global optimizer.
        **kwargs
            Extra arguments forwarded to the optimizer.

        Returns
        -------
        lambda_opt : float
            Optimal regularization parameter.
        result : `~scipy.optimize.OptimizeResult`
            Optimizer result object returned by :obj:`~scipy.optimize.basinhopping`.
        """
        self._solver = solver
        init_logbeta = 0.5 * (bounds[0] + bounds[1])
        res: OptimizeResult = basinhopping(
            lambda logb: self.gcv(solver, 10 ** logb[0]),
            x0=[init_logbeta],
            minimizer_kwargs={"bounds": [bounds]},  # type: ignore[arg-type]
            stepsize=stepsize,
            **kwargs,
        )
        return float(10 ** res.x[0]), res

    @overload
    def plot_gcv(
        self,
        solver: _SVDBase | None = None,
        axes: None = None,
        bounds: Collection[float | None] | None = None,
        n_beta: int = 500,
        show_min_line: bool = True,
    ) -> tuple[matplotlib.axes.Axes, matplotlib.figure.Figure]: ...

    @overload
    def plot_gcv(
        self,
        solver: _SVDBase | None = None,
        axes: matplotlib.axes.Axes | None = None,
        bounds: Collection[float | None] | None = None,
        n_beta: int = 500,
        show_min_line: bool = True,
    ) -> matplotlib.axes.Axes: ...

    def plot_gcv(
        self,
        solver: _SVDBase | None = None,
        axes: matplotlib.axes.Axes | None = None,
        bounds: Collection[float | None] | None = None,
        n_beta: int = 500,
        show_min_line: bool = True,
    ) -> tuple[matplotlib.axes.Axes, matplotlib.figure.Figure] | matplotlib.axes.Axes:
        r"""Plot GCV as a function of the regularization parameter.

        Parameters
        ----------
        solver
            An `~._SVDBase` instance. If ``None``, the last solver used in :meth:`optimize` is used.
        axes
            Matplotlib axes to plot on. If ``None``, a new figure and axes are created.
        bounds
            Boundary pair of log10 of regularization parameters, by default None.
            If None, the bounds are generated by the solver as described in ``SVD._generate_bounds()``.
            If you set the bounds like ``(-10, None)``, the higher bound is set to
            :math:`\log_{10}\sigma_1^2`.
            Raise an error if a >= b in (a, b).
        n_beta
            Number of regularization parameters, by default 500.
        show_min_line
            Whether to show a vertical line at the optimal regularization parameter.

        Returns
        -------
        axes : :obj:`~matplotlib.axes.Axes`
            A matplotlib Axes object.
        fig : :obj:`~matplotlib.figure.Figure`
            A matplotlib figure object if axes is None, otherwise None.
        """
        solver = self._resolve_solver(solver)

        if axes is None:
            fig, axes = plt.subplots()
        else:
            fig = None

        bounds_resolved = solver._generate_bounds(bounds)
        lambdas = np.logspace(*bounds_resolved, n_beta)
        gcvs = np.array([self.gcv(solver, beta) for beta in lambdas])

        axes.loglog(lambdas, gcvs, color="C0", zorder=0)

        if solver.lambda_opt is not None and show_min_line:
            axes.axvline(solver.lambda_opt, color="r", linestyle="dashed", linewidth=1, zorder=1)

        axes.set_xlim(lambdas.min(), lambdas.max())
        axes.set_xlabel(r"Regularization parameter, $\lambda$")
        axes.tick_params(axis="both", which="both", direction="in", top=True, right=True)

        return (axes, fig) if fig is not None else axes
