name: Run test ✅

on:
  pull_request:
    branches: [main]

jobs:
  pytest:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        environment: [py39, py310, py311, py312]
    runs-on: ${{ matrix.os }}

    steps:
    - name: check out repo
      uses: actions/checkout@v4

    - name: Set up Pixi 🟨
      uses: prefix-dev/setup-pixi@v0.8.0
      with:
        environments: ${{ matrix.environment }}

    # pytest -> JUnit xml format
    - name: Execute pytest ✅ with 🐍 ${{ matrix.environment }} - ${{ matrix.os }}
      run: |
        pixi run --environment ${{ matrix.environment }} postinstall-e
        pixi run --environment ${{ matrix.environment }} test --junit-xml results/pytest.xml
      continue-on-error: true

    - name: Upload PyTest Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: PyTest Results (${{ matrix.environment }} - ${{ matrix.os }})
        path: results/*.xml

    - name: Download Artifacts
      if: success() || failure()
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        junit_files: artifacts/**/*.xml
